/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.twincoder.ide.ui;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import org.twincoder.ide.utils.TwinCoderUtils;


/**
 *
 * @author Gabriel
 */
public class Browser extends javax.swing.JPanel {

    private MainScreen mainScreen;
    /**
     * Creates new form PharosBrowser
     * @param mainScreen
     * @param resource
     */
    public Browser(MainScreen mainScreen) {
        initComponents();
        this.mainScreen = mainScreen;
        
        jEditorPaneBrowser.addHyperlinkListener((HyperlinkEvent e) -> {
            if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                if (e.getURL() == null) {
                    String resource = e.getDescription();
                    mainScreen.openResource(resource);
                } else {
                    TwinCoderUtils.openWebpage(e.getURL());
                }
            }
        });
    }

    public void loadUrl(URL url) {
        try {
            jEditorPaneBrowser.setPage(url);
        } catch (IOException ex) {
            Logger.getLogger(Browser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadContent(String content) {
        if (content != null) {
            jEditorPaneBrowser.setText(content);
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneBrowser = new javax.swing.JScrollPane();
        jEditorPaneBrowser = new javax.swing.JEditorPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        jEditorPaneBrowser.setEditable(false);
        jEditorPaneBrowser.setContentType("text/html"); // NOI18N
        jEditorPaneBrowser.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n          Browser content\n    </p>\r\n  </body>\r\n</html>\r\n");
        jScrollPaneBrowser.setViewportView(jEditorPaneBrowser);

        add(jScrollPaneBrowser, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPaneBrowser;
    private javax.swing.JScrollPane jScrollPaneBrowser;
    // End of variables declaration//GEN-END:variables
}
