/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.twincoder.ide.ui;

import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author Gabriel
 */
public class CloseableTabTitle extends javax.swing.JPanel {
    
    private final JTabbedPane pane;
    private final MainScreen mainScreen;
    /**
     * Creates new form TabPanel
     * @param pane
     * @param mainScreen
     */
    public CloseableTabTitle(final JTabbedPane pane, final MainScreen mainScreen, final ImageIcon icon) {

      
        // Set reference to the pane
        if (pane == null || mainScreen == null) {
            throw new NullPointerException("TabbedPane or Main Screen is null");
        }
        this.pane = pane;
        this.mainScreen = mainScreen;
         
        //make JLabel read titles from JTabbedPane
        JLabel label = new JLabel() {
            public String getText() {
                int i = pane.indexOfTabComponent(CloseableTabTitle.this);
                if (i != -1) {
                    return pane.getTitleAt(i);
                }
                return null;
            }
        };
        label.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 5));
        if (icon != null) {
            label.setIcon(icon);
        }
        this.add(label);
        this.add(new CloseButton());
        initComponents();
    }
    
    // Create the close button
    private class CloseButton extends JButton implements ActionListener {
        public CloseButton() {
            setPreferredSize(new Dimension(15, 15));
            setToolTipText("Close this tab");
            
            //Make the button looks the same for all Laf's
            setUI(new BasicButtonUI());
            
            //Make it transparent
            setContentAreaFilled(false);
            setFocusable(false);
            setBorder(BorderFactory.createEmptyBorder(2, 0, 0, 0));            
            setBorderPainted(false);            
            setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close-button.png")));
            
            // Rollover effect
            setRolloverEnabled(true);
            setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close-button-rollover.png")));

            //We use the same listener for all buttons
            //addMouseListener(buttonMouseListener);
            
            //Close the proper tab by clicking the button
            addActionListener(this);
        }
 
        @Override
        public void actionPerformed(ActionEvent e) {
            int i = pane.indexOfTabComponent(CloseableTabTitle.this);
            if (i != -1) {
                mainScreen.close(pane.getComponentAt(i));
            }
        }
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 0, 0));
        setOpaque(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
