/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.twincoder.ide.ui;

import org.twincoder.ide.program.ProjectProperties;

/**
 *
 * @author gbornia
 */
public class PropertiesScreen extends javax.swing.JFrame {

    ProjectProperties properties;
    
    /**
     * Creates new form PropertiesScreen
     */
    public PropertiesScreen() {
        initComponents();
        
        properties = ProjectProperties.getProjectProperties();
        jCheckBoxAutoOpen.setSelected(properties.isFileAutoOpen());
        jCheckBoxCache.setSelected(properties.isCacheResources());
        jTextFieldCacheFolder.setText(properties.getCacheFolder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxCache = new javax.swing.JCheckBox();
        jTextFieldCacheFolder = new javax.swing.JTextField();
        jCheckBoxAutoOpen = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TwinCoder Properties");
        setAlwaysOnTop(true);

        jPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel.setMinimumSize(new java.awt.Dimension(600, 450));
        jPanel.setPreferredSize(new java.awt.Dimension(600, 450));
        java.awt.GridBagLayout jPanelLayout = new java.awt.GridBagLayout();
        jPanelLayout.rowHeights = new int[] {25, 50, 25, 25, 25};
        jPanel.setLayout(jPanelLayout);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Folder:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel.add(jLabel1, gridBagConstraints);

        jCheckBoxCache.setText("Cache images, audio and other remote files");
        jCheckBoxCache.setMargin(new java.awt.Insets(1, 0, 0, 1));
        jCheckBoxCache.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBoxCache.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel.add(jCheckBoxCache, gridBagConstraints);

        jTextFieldCacheFolder.setPreferredSize(new java.awt.Dimension(450, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        jPanel.add(jTextFieldCacheFolder, gridBagConstraints);

        jCheckBoxAutoOpen.setText("Automatically open last opened files");
        jCheckBoxAutoOpen.setMargin(new java.awt.Insets(1, 0, 0, 1));
        jCheckBoxAutoOpen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBoxAutoOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAutoOpenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel.add(jCheckBoxAutoOpen, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Cache Properties");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("General Properties");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel.add(jLabel3, gridBagConstraints);

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        jPanelButtons.setMinimumSize(new java.awt.Dimension(209, 40));
        jPanelButtons.setPreferredSize(new java.awt.Dimension(20, 40));
        jPanelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonSave.setText("Save & Close");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonSave);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonClose);

        getContentPane().add(jPanelButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        properties.setFileAutoOpen(jCheckBoxAutoOpen.isSelected());
        properties.setCacheResources(jCheckBoxCache.isSelected());
        properties.setCacheFolder(jTextFieldCacheFolder.getText());
        properties.save();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jCheckBoxAutoOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAutoOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAutoOpenActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxAutoOpen;
    private javax.swing.JCheckBox jCheckBoxCache;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JTextField jTextFieldCacheFolder;
    // End of variables declaration//GEN-END:variables
}
